web/esoe_oop_judge/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('judge.urls')),
]

web/judge/urls.py
from django.conf.urls import url

from . import views
from django.urls import path


app_name = 'judge'

urlpatterns = [
    path('',
         views.index,
         name='index'),

    path('login/',
         views.login,
         name='login'),

    path('logout/',
         views.logout,
         name='logout'),

    path('problems/',
         views.problem_list,
         name='problem_list'),

    path('problems/<str:pk>/',
         views.problem_detail,
         name='problem_detail'),

    path('profile/',
         views.profile,
         name='profile'),

    path('submissions/<str:pk>/',
         views.submission_detail,
         name='submission_detail'),
]

web/judge/models.py
from django.db import models
from django.core.validators import validate_slug

from django.contrib.auth.models import User


class Course(models.Model):
    name = models.CharField(max_length=32, default='')
    
    def __str__(self):
        return '[#{}][profile size={}]'.format(self.name, self.profiles.count())

class Problem(models.Model):
    # this is convenient when you are now constructing a problem and don't want
    # users to see it for the time being
    staff_viewable_only = models.BooleanField(default=False)

    name = models.CharField(primary_key=True, blank=False, max_length=32)
    title = models.CharField(max_length=32)

    course = models.ForeignKey(Course, related_name='problems',
        blank=True, null=True, on_delete=models.SET_NULL)

    description = models.TextField()

    input_format = models.TextField()
    output_format = models.TextField()
    
    sample_input = models.TextField()
    sample_output = models.TextField()

    deadline_datetime = models.DateTimeField()

    language = models.CharField(max_length=2,
                                choices=[('CP', 'C++'),
                                         ('PY', 'Python'),
                                         ('JA', 'Java')],
                                default='JA')

    def __str__(self):
        return self.brief()
    
    def brief(self):
        return '[#{}][Course={}] {}'.format(
            self.name,
            self.course.name,
            self.title
        )
    
    def detail(self):
        r = ''
        r += 'staff_viewable_only: ' + str(self.staff_viewable_only) + '\n'
        r += 'course: ' + self.group + '\n'
        r += 'name: ' + self.name + '\n'
        r += 'title: ' + self.title + '\n'
        r += 'deadline_datetime: ' + str(self.deadline_datetime) + '\n'
        r += 'language: ' + self.language + '\n'
        return r

    class Meta:
        ordering = ['pk']


class RequiredFile(models.Model):
    problem = models.ForeignKey(Problem, related_name = 'required_files', on_delete=models.CASCADE)

    filename = models.CharField(max_length=32)
    via = models.CharField(max_length=1,
                           choices=[('S', 'Submitted'),
                                    ('P', 'Provided')])

    def __str__(self):
        return '[#{}][Problem={{{}}}] {} ({})'.format(
            self.pk,
            str(self.problem),
            self.filename,
            self.get_via_display()
        )

    class Meta:
        ordering = ['problem__pk', 'via', 'filename']


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, 
        related_name='profile', primary_key=True)
    
    courses = models.ManyToManyField(Course, related_name='profiles', blank=True)

    name = models.CharField(max_length=32)

    github_account = models.CharField(max_length=32,
                                      blank=True,
                                      validators=[validate_slug])
    github_repository = models.CharField(max_length=32,
                                         blank=True,
                                         validators=[validate_slug])

    solved_problems = models.ManyToManyField(Problem,
                                             related_name='solved_profiles',
                                             blank=True)

    def __str__(self):
        return '[#{}][User={}][Courses={}] {}'.format(
            self.pk,
            self.user,
            ', '.join([i.name for i in self.courses.all()])
                if self.courses.exists() else None,
            self.name
        )
    
    class Meta:
        ordering = ['user__username']


class Submission(models.Model):
    problem = models.ForeignKey(Problem, on_delete=models.CASCADE)
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)

    status = models.CharField(max_length=2,
                              choices=[('FE', 'Format Error'),
                                       ('SU', 'Submitting'),
                                       ('SE', 'Submission Error'),
                                       ('CO', 'Compiling'),
                                       ('CE', 'Compilation Error'),
                                       ('JU', 'Judging'),
                                       ('AC', 'Accepted'),
                                       ('WA', 'Wrong Answer'),
                                       ('RE', 'Runtime Error')],
                              default='SU')
    submission_datetime = models.DateTimeField()

    # detailed_messages = models.TextField(blank=True)
    message = models.TextField(blank=True)

    def __str__(self):
        return '[#{}][Problem={{{}}}][Profile={{{}}}]'.format(
            self.pk,
            str(self.problem),
            str(self.profile)
        )
    
    def has_message(self):
        return bool(self.message)
    
    def get_message_header(self):        
        if self.status == 'WA':
            return 'The following mismatches occurred during comparison:'
        
        if self.status == 'RE':
            return 'The following errors occurred during execution:'
        
        return self.get_status_display() + ':'
    
    def get_message(self):
        return self.message

    class Meta:
        ordering = ['-pk']

web/judge/forms.py
from .models import Profile

from django.forms import ModelForm


class ProfileUpdateGithubForm(ModelForm):
    class Meta:
        model = Profile
        fields = ['github_account', 'github_repository']

web/judge/views.py
import os
import sys
import subprocess

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
import config

from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render, get_object_or_404
from django.contrib import messages
from django.utils import timezone
from django.contrib.auth.decorators import login_required

from django.db.models import Max
from django.contrib.auth.models import User
from .models import Problem, Submission

from django.contrib.auth import views as auth_views

from django.contrib.auth.forms import PasswordChangeForm
from .forms import ProfileUpdateGithubForm


@login_required
def index(request):
    # you may change this to use a different problem as sample problem
    sample_problem = Problem.objects.all()[0]

    return render(request,
                  'judge/index.html',
                  {'github_account': config.GITHUB_ACCOUNT,
                   'sample_problem': sample_problem})


def login(request):
    # users should not be able to log in again if they're already logged in
    if request.user.is_authenticated:
        messages.error(request,
                       'You are already logged in.')
        return HttpResponseRedirect(reverse('judge:index'))
    else:
        return auth_views.LoginView.as_view(template_name='judge/login.html')(request)


def logout(request):
    # users should not be able to log out if they're not logged in yet
    if not request.user.is_authenticated:
        messages.error(request,
                       'You are not logged in yet.')
        return HttpResponseRedirect(reverse('judge:index'))
    else:
        return auth_views.LogoutView.as_view(next_page='judge:index')(request)


@login_required
def problem_list(request):
    user = request.user
    profile = user.profile

    problem_info_list = []

    for course in user.profile.courses.all():
        for problem in course.problems.all():
            if problem.staff_viewable_only and not user.is_staff:
                continue

            profile_solved = profile.solved_problems.filter(pk=problem.pk).exists()
            problem_info_list.append({
                'problem': problem,
                'profile_solved': profile_solved
            })

    return render(request,
                  'judge/problem_list.html',
                  {'problem_info_list': problem_info_list})


@login_required
def problem_detail(request, pk):
    user = request.user
    profile = user.profile

    problem = get_object_or_404(Problem, pk=pk)

    if problem.staff_viewable_only and not user.is_staff:
        messages.error(request, 'Permission denied.')
        return HttpResponseRedirect(reverse('judge:index'))
    
    if problem.course == None or not user.profile.courses.filter(pk = problem.course.pk).exists():
        messages.error(request, 'Permission denied.')
        return HttpResponseRedirect(reverse('judge:index'))

    profile_submission_list = problem.submission_set.filter(profile=profile)
    profile_solved = profile.solved_problems.filter(pk=problem.pk).exists()

    submitted_file_info_list = []
    for f in problem.required_files.filter(via='S'):
        submitted_file_info_list.append({'filename': f.filename})
    
    provided_file_info_list = []
    for f in problem.required_files.filter(via='P'):
        provided_file_info_list.append({
            'filename': f.filename,
            'static_path': os.path.join(
                os.path.basename(config.JUDGE_STATIC_PROBLEMS_DIR),
                str(problem.pk),
                f.filename
            )
        })

    # handle submission
    if request.method == 'POST':
        now = timezone.now()

        # no submissions are allowed after deadline
        if now > problem.deadline_datetime:
            messages.error(request, 'Sorry, it is already over the deadline.')
        else:
            submission = Submission(problem=problem,
                                    profile=profile,
                                    submission_datetime=now)
            submission.save()

            # judge (without waiting)
            subprocess.Popen([os.path.join(config.VIRTUALENV_BIN_DIR, 'python'),
                              os.path.join(config.JUDGE_BIN_DIR, 'judge.py'),
                              str(submission.pk)])

            messages.success(request, 'Submitting. Refresh to see the results.')
        return HttpResponseRedirect(reverse('judge:problem_detail', kwargs={'pk': pk}))

    return render(request,
                  'judge/problem_detail.html',
                  {'problem': problem,
                   'profile_submission_list': profile_submission_list,
                   'profile_solved': profile_solved,
                   'submitted_file_info_list': submitted_file_info_list,
                   'provided_file_info_list': provided_file_info_list})


@login_required
def profile(request):
    user = request.user
    profile = user.profile

    # unbound forms to be used later
    unbound_update_github_form = ProfileUpdateGithubForm(instance=profile,
                                                         initial={'github_account':
                                                                  profile.github_account,
                                                                  'github_repository':
                                                                  profile.github_repository})
    unbound_password_change_form = PasswordChangeForm(user=user)

    # handle forms
    if request.method == 'POST':
        update_github_form = ProfileUpdateGithubForm(data=request.POST,
                                                     instance=profile,
                                                     initial={'github_account':
                                                              profile.github_account,
                                                              'github_repository':
                                                              profile.github_repository})
        password_change_form = PasswordChangeForm(data=request.POST, user=user)

        # for it to be regarded as successful (such that the user gets
        # redirected back to profile), all changed forms must be valid and saved
        # already; otherwise, render the view with all forms again (with
        # unchanged ones replaced by unbound ones, so as to clean their errors),
        # in order for the user to know what errors have occurred
        n_undone_forms = update_github_form.has_changed() + password_change_form.has_changed()

        if update_github_form.has_changed():
            if update_github_form.is_valid():
                update_github_form.save()
                n_undone_forms -= 1

                messages.success(request,
                                 'GitHub settings successfully updated.')
        else:
            update_github_form = unbound_update_github_form

        if password_change_form.has_changed():
            if password_change_form.is_valid():
                password_change_form.save()
                n_undone_forms -= 1

                messages.success(request,
                                 'Password successfully changed. Please log in again.')
        else:
            password_change_form = unbound_password_change_form

        if n_undone_forms == 0:
            return HttpResponseRedirect(reverse('judge:profile'))
    else:
        update_github_form = unbound_update_github_form
        password_change_form = unbound_password_change_form

    return render(request,
                  'judge/profile.html',
                  {'profile': profile,
                   'update_github_form': update_github_form,
                   'password_change_form': password_change_form})


@login_required
def submission_detail(request, pk):
    user = request.user
    profile = user.profile

    submission = get_object_or_404(Submission, pk=pk)

    # if the profile isn't the owner of this submission, and it isn't a staff
    # either, then it shouldn't see this submission
    if submission.profile != profile and not user.is_staff:
        messages.error(request,
                       'Permission denied.')
        return HttpResponseRedirect(reverse('judge:index'))

    # display submitted files (only when status != 'SU' and status != 'SE')
    submitted_file_info_list = []
    if submission.status != 'SU' and submission.status != 'SE':
        submitted_filenames = [f.filename for f in submission.problem.required_files.filter(via='S')]
        for filename in submitted_filenames:
            # here, we specifically open the file in binary mode, read it, and
            # then decode it with UTF-8, such that reading submitted files in
            # other encodings (for example, those uploaded from Windows) won't
            # cause a problem
            with open(os.path.join(config.JUDGE_SUBMISSIONS_DIR, str(submission.pk), filename), 'rb') as f:
                submitted_file_info_list.append({
                    'filename': filename,
                    'content': f.read().decode('utf-8', 'replace')
                })

    return render(request,
                  'judge/submission_detail.html',
                  {'submission': submission,
                   'submitted_file_info_list': submitted_file_info_list})

web/judge/templates/judge/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">

    <title>ESOE OOP Judge [GitHub edition]</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'judge/css/base.css' %}">
    {% block css %}
    {% endblock %}

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    {% block js %}
    {% endblock %}
  </head>
  <body>
    {% if user.is_authenticated %}
    <nav class="navbar navbar-custom navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="{% url 'judge:index' %}">ESOE OOP Judge  [GitHub edition]</a>
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'judge:problem_list' %}">Problems</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="{% url 'judge:profile' %}"><span class="glyphicon glyphicon-user"></span> {{ user.username }}</a></li>
            <li><a href="{% url 'judge:logout' %}"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
          </ul>
        </div>
      </div>
    </nav>
    {% endif %}

    <div class="container-fluid">
        <div class="row">
          <div class="col-sm-offset-1 col-sm-10">
            {% if messages %}
            <div id="messages-div">
              {% for message in messages %}
              <div class="alert {{ message.tags }} alert-dismissible fade in">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert"><span>&times;</span></button>
              </div>
              {% endfor %}
            </div>
            {% endif %}

            {% block content %}
            {% endblock %}
          </div>
        </div>
    </div>

    <footer class="footer">
      <div class="container-fluid">
        <h6 class="text-center">
          Developed by Hao-Ying Liang (梁浩穎) and Wei-Cheng Li (李蔚成).<br>
          Modified by <a target="_blank" href="https://github.com/jc-hiroto">jc-hiroto</a> (張博皓) and <a target="_blank" href="https://github.com/Tetrapod1206">Tetrapod1206</a> (蕭博瀚).
          / Special thanks to 108-2 OOP course TA Wang-Ting (王婷) for assistance.<br>
          Credits to <a target="_blank" href="http://ada2015.csie.org">ADA2015</a> for inspiration.
        <h6>
      </div>
    </footer>
  </body>
</html>

web/judge/templates/judge/index.html
{% extends 'judge/base.html' %}

{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'judge/css/index.css' %}">
{% endblock %}

{% block content %}
<div id="guidelines">
  <h2>How to submit?</h2>
  <ol>
    <li>
      Register an account at
      <a target="_blank" href="https://github.com">GitHub</a>.
    </li>
    <li>
      Create a new private repository for this course.
    </li>
    <li>
      Add the account<code>{{ github_account }}</code> as a collaborator in your repository Settings -> Manage access.
    </li>
    <li>
      Set up the GitHub settings in
      <a href="{% url 'judge:profile' %}">your profile</a>.
    </li>
    <li>
      Clone the repository into whatever place you like
      (<code>git clone</code>).
    </li>
    <li>
      In the directory you just cloned, create another directory named
      <code>{{ sample_problem.pk }}</code>, which is the problem ID of
      <a href={% url 'judge:problem_detail' pk=sample_problem.pk %}>{{ sample_problem.title }}</a>.
    </li>
    <li>
      Add all required files marked submitted in
      <a href={% url 'judge:problem_detail' pk=sample_problem.pk %}>{{ sample_problem.title }}</a>
      into <code>{{ sample_problem.pk }}</code> (with your solutions included,
      of course).
    </li>
    <li>
      Commit and push
      (<code>git add</code>, <code>git commit</code>, and then <code>git push</code>).
    </li>
    <li>
      Click the submit button in
      <a href={% url 'judge:problem_detail' pk=sample_problem.pk %}>{{ sample_problem.title }}</a>.
    </li>
    <li>
      See if there are any errors; if so, then go back to debug and try it again
      when you are done.
    </li>
  </ol>
  <div class="alert alert-warning">
    Here, we use
    <a href={% url 'judge:problem_detail' pk=sample_problem.pk %}>{{ sample_problem.title }}</a>
    as sample. Do not forget to make corresponding changes when you are solving
    other problems.
  </div>
</div>
{% endblock %}

web/judge/templates/judge/login.html
{% extends 'judge/base.html' %}

{% load static %}
{% load widget_tweaks %}

{% block css %}
<link rel="stylesheet" href="{% static 'judge/css/login.css' %}">
{% endblock %}

{% block content %}
<h1 class="text-center">ESOE OOP Judge</h1>

<form method="post" action="{% url 'judge:login' %}" class="center-block">
  {% csrf_token %}

  {{ form.non_field_errors }}
  <div class="form-group{% if form.non_field_errors or form.username.errors %} has-error{% endif %}">
    <label for="{{ form.username.id_for_label }}">{{ form.username.label }}</label>
    <div class="inner-addon left-addon">
      <span class="glyphicon glyphicon-user"></span>
      {% render_field form.username placeholder=form.username.label autofocus='' class+='form-control' %}
    </div>
    {{ form.username.errors }}
  </div>
  <div class="form-group{% if form.non_field_errors or form.password.errors %} has-error{% endif %}">
    <label for="{{ form.password.id_for_label }}">{{ form.password.label }}</label>
    <div class="inner-addon left-addon">
      <span class="glyphicon glyphicon-lock"></span>
      {% render_field form.password placeholder=form.password.label class+='form-control' %}
    </div>
    {{ form.password.errors }}
  </div>

  <input type="hidden" name="next" value="{{ next }}">

  <button class="btn btn-primary btn-lg btn-block" type="submit">Login</button>
</form>
{% endblock %}

web/judge/templates/judge/problem_detail.html
{% extends 'judge/base.html' %}

{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'judge/css/problem_detail.css' %}">
{% endblock %}

{% block js %}
<script type="text/javascript" src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>
{% endblock %}

{% block content %}
<h2 class="text-center">{{ profile_solved|yesno:'[Solved] ,' }}{{ problem.title }}</h2>

<h3>Deadline</h3>
<p>{{ problem.deadline_datetime }}.</p>

<h3>Description</h3>
{{ problem.description|linebreaks }}

<h3>Input Format</h3>
{{ problem.input_format|linebreaks }}

<h3>Output Format</h3>
{{ problem.output_format|linebreaks }}

<h3>Sample Input</h3>
<pre><code>{{ problem.sample_input }}</code></pre>

<h3>Sample Output</h3>
<pre><code>{{ problem.sample_output }}</code></pre>

<h3>Required Files</h3>
<div id="required-files">
  <ul>
    {% for submitted_file_info in submitted_file_info_list %}
    <li><tt>{{ submitted_file_info.filename }}</tt> (Submitted)</li>
    {% endfor %}
    {% for provided_file_info in provided_file_info_list %}
    <li><a target="_blank" href="{% static provided_file_info.static_path %}"><tt>{{ provided_file_info.filename }}</tt></a> (Provided)</li>
    {% endfor %}
  </ul>
</div>

<form method="post" action="{% url 'judge:problem_detail' problem.pk %}">
  {% csrf_token %}

  <button class="btn btn-primary btn-lg" type="submit">Submit</button>
</form>

<h3>My Submissions</h3>
<div class="table-responsive">
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th class="table-column-id">ID</th>
        <th class="table-column-problem">Problem</th>
        <th class="table-column-status">Status</th>
        <th class="table-column-datetime">Datetime</th>
      </tr>
    </thead>
    <tbody>
      {% for submission in profile_submission_list %}
      <tr>
        <td class="table-column-id"><a href="{% url 'judge:submission_detail' submission.pk %}">{{ submission.pk }}</a></td>
        <td class="table-column-problem">{{ submission.problem.title }}</td>
        <td class="table-column-status">{{ submission.get_status_display }}</td>
        <td class="table-column-datetime">{{ submission.submission_datetime }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

web/judge/templates/judge/problem_list.html
{% extends 'judge/base.html' %}

{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'judge/css/problem_list.css' %}">
{% endblock %}

{% block content %}
<div class="table-responsive">
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th class="table-column-course">Course</th>
        <th class="table-column-title">Title</th>
        <th class="table-column-solved">Solved</th>
        <th class="table-column-deadline">Deadline</th>
      </tr>
    </thead>
    <tbody>
      {% for problem_info in problem_info_list %}
      <tr>
        <td class="table-column-course">{{ problem_info.problem.course.name }}</td>
        <td class="table-column-title"><a href="{% url 'judge:problem_detail' problem_info.problem.pk %}">{{ problem_info.problem.title }}</a></td>
        <td class="table-column-solved">
          {% if problem_info.profile_solved %}
          <span class="glyphicon glyphicon-ok text-success"></span>
          {% else %}
          <span class="glyphicon glyphicon-remove text-danger"></span>
          {% endif %}
        </td>
        <td class="table-column-deadline">{{ problem_info.problem.deadline_datetime }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

web/judge/templates/judge/profile.html
{% extends 'judge/base.html' %}

{% load static %}
{% load widget_tweaks %}

{% block css %}
<link rel="stylesheet" href="{% static 'judge/css/profile.css' %}">
{% endblock %}

{% block content %}
<h2>{{ profile.user.username }} ({{ profile.name }})</h2>

<form method="post" action="{% url 'judge:profile' %}">
  {% csrf_token %}

  <h3>GitHub Settings & Change Password</h3>
  {{ update_github_form.non_field_errors }}
  <div class="row">
    <div class="form-group{% if update_github_form.non_field_errors or update_github_form.github_account.errors %} has-error{% endif %} col-sm-6">
      {% with update_github_form.github_account.label|add:' (in lower case)' as label %}
      <label for="{{ update_github_form.github_account.id_for_label }}">{{ label }}</label>
      <div class="inner-addon left-addon">
        <span class="fa fa-github"></span>
        {% render_field update_github_form.github_account placeholder=label class+='form-control' %}
      </div>
      {% endwith %}
      {{ update_github_form.github_account.errors }}
    </div>
    <div class="form-group{% if update_github_form.non_field_errors or update_github_form.github_repository.errors %} has-error{% endif %} col-sm-6">
      {% with update_github_form.github_repository.label|add:' (in lower case)' as label %}
      <label for="{{ update_github_form.github_repository.id_for_label }}">{{ label }}</label>
      <div class="inner-addon left-addon">
        <span class="fa fa-github"></span>
        {% render_field update_github_form.github_repository placeholder=label class+='form-control' %}
      </div>
      {% endwith %}
      {{ update_github_form.github_repository.errors }}
    </div>
  </div>
  {{ password_change_form.non_field_errors }}
  <div class="row">
    <div class="form-group{% if password_change_form.non_field_errors or password_change_form.old_password.errors %} has-error{% endif %} col-sm-4">
      <label for="{{ password_change_form.old_password.id_for_label }}">{{ password_change_form.old_password.label }}</label>
      <div class="inner-addon left-addon">
        <span class="glyphicon glyphicon-lock"></span>
        {% render_field password_change_form.old_password placeholder=password_change_form.old_password.label class+='form-control' %}
      </div>
      {{ password_change_form.old_password.errors }}
    </div>
    <div class="form-group{% if password_change_form.non_field_errors or password_change_form.new_password1.errors %} has-error{% endif %} col-sm-4">
      <label for="{{ password_change_form.new_password1.id_for_label }}">{{ password_change_form.new_password1.label }}</label>
      <div class="inner-addon left-addon">
        <span class="glyphicon glyphicon-lock"></span>
        {% render_field password_change_form.new_password1 placeholder=password_change_form.new_password1.label class+='form-control' %}
      </div>
      {{ password_change_form.new_password1.errors }}
    </div>
    <div class="form-group{% if password_change_form.non_field_errors or password_change_form.new_password2.errors %} has-error{% endif %} col-sm-4">
      <label for="{{ password_change_form.new_password2.id_for_label }}">{{ password_change_form.new_password2.label }}</label>
      <div class="inner-addon left-addon">
        <span class="glyphicon glyphicon-lock"></span>
        {% render_field password_change_form.new_password2 placeholder=password_change_form.new_password2.label class+='form-control' %}
      </div>
      {{ password_change_form.new_password2.errors }}
    </div>
  </div>

  <button class="btn btn-primary btn-lg" type="submit">Update</button>
</form>

<h3>My Submissions</h3>
<div class="table-responsive">
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th class="table-column-id">ID</th>
        <th class="table-column-problem">Problem</th>
        <th class="table-column-status">Status</th>
        <th class="table-column-datetime">Datetime</th>
      </tr>
    </thead>
    <tbody>
      {% for submission in profile.submission_set.all %}
      <tr>
        <td class="table-column-id"><a href="{% url 'judge:submission_detail' submission.pk %}">{{ submission.pk }}</a></td>
        <td class="table-column-problem"><a href="{% url 'judge:problem_detail' submission.problem.pk %}">{{ submission.problem.title }}</a></td>
        <td class="table-column-status">{{ submission.get_status_display }}</td>
        <td class="table-column-datetime">{{ submission.submission_datetime }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}